  
# Site settings
title: Stanford Irish Association
#author:
#  name: Brian Higgins
#  email: higginsb@stanford.edu
#description: "Hello world."

# Build settings
remote_theme: jekyll/minima
# Non remote themes
# theme:

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/higginsbrian/Stanford-Irish-Association" }
    - { platform: twitter, user_url: "https://twitter.com/irishstanford" }
    

